/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company.pbo.ServiceFunction;


import com.company.pbo.DBandConnect.clsService;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;    
import java.sql.ResultSet;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author Mihaly
 */
public class formService extends javax.swing.JFrame {
    int ID;
    String Username;
    boolean toogle = false;

    /**
     * Creates new form formDaftarService
     */
    public formService(int ID, String Username) {
        this.ID = ID;
        this.Username = Username;
        initComponents();
        IsiTabel();
        isiCboStatus();
        IsiCboProgress();
        btnConfirmEdit.setVisible(false);
        btnCancel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ServiceTable = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        LabelStatus = new javax.swing.JLabel();
        CboStatus = new javax.swing.JComboBox<>();
        LabelProgress = new javax.swing.JLabel();
        cboProgress = new javax.swing.JComboBox<>();
        btnConfirmEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        LabelSKU1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evoker Service");
        setBackground(new java.awt.Color(40, 43, 48));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(40, 43, 48));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setForeground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ServiceTable.setBackground(new java.awt.Color(102, 102, 102));
        ServiceTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ServiceTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ServiceTable.setForeground(new java.awt.Color(255, 255, 255));
        ServiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "X401D", "ASUS", "Kelvin", "081255519273", "11/12/22", "Sedang Diperiksa Oleh Petugas", "Dylan", "24", "Proses", null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SID", "SKU", "Brand", "Nama Pelanggan", "No. Telepon", "Tanggal Masuk", "Status", "Petugas", "ID Petugas", "Progress", "Tanggal Selesai"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ServiceTable.setToolTipText("");
        ServiceTable.setGridColor(new java.awt.Color(0, 0, 0));
        ServiceTable.setRowHeight(50);
        ServiceTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        ServiceTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ServiceTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ServiceTable.setShowGrid(true);
        ServiceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServiceTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ServiceTable);
        if (ServiceTable.getColumnModel().getColumnCount() > 0) {
            ServiceTable.getColumnModel().getColumn(0).setResizable(false);
            ServiceTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            ServiceTable.getColumnModel().getColumn(2).setResizable(false);
            ServiceTable.getColumnModel().getColumn(3).setResizable(false);
            ServiceTable.getColumnModel().getColumn(4).setResizable(false);
            ServiceTable.getColumnModel().getColumn(5).setResizable(false);
            ServiceTable.getColumnModel().getColumn(6).setResizable(false);
            ServiceTable.getColumnModel().getColumn(6).setPreferredWidth(258);
            ServiceTable.getColumnModel().getColumn(7).setResizable(false);
            ServiceTable.getColumnModel().getColumn(8).setResizable(false);
            ServiceTable.getColumnModel().getColumn(9).setResizable(false);
            ServiceTable.getColumnModel().getColumn(10).setResizable(false);
        }

        btnEdit.setBackground(new java.awt.Color(0, 0, 153));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        LabelStatus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        LabelStatus.setText("Status:");

        CboStatus.setBackground(new java.awt.Color(153, 153, 153));
        CboStatus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CboStatus.setForeground(new java.awt.Color(255, 255, 255));
        CboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CboStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CboStatusMouseClicked(evt);
            }
        });
        CboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboStatusActionPerformed(evt);
            }
        });

        LabelProgress.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelProgress.setForeground(new java.awt.Color(255, 255, 255));
        LabelProgress.setText("Progress:");

        cboProgress.setBackground(new java.awt.Color(153, 153, 153));
        cboProgress.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cboProgress.setForeground(new java.awt.Color(255, 255, 255));
        cboProgress.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboProgress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboProgressMouseClicked(evt);
            }
        });

        btnConfirmEdit.setBackground(new java.awt.Color(0, 153, 0));
        btnConfirmEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmEdit.setText("Confirm Edit");
        btnConfirmEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmEditActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 0, 153));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel Edit/New");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        LabelSKU1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelSKU1.setForeground(new java.awt.Color(255, 255, 255));
        LabelSKU1.setText("Cari:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LabelStatus)
                    .addComponent(LabelProgress))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(CboStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cboProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelSKU1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 519, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(btnConfirmEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1907, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSKU1)
                    .addComponent(CboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelStatus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelProgress)
                    .addComponent(btnConfirmEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(303, 303, 303)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
        );

        jMenuBar1.setForeground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("File");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem3.setText("Back to Main Menu");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //user defined code
    
    private void searchTable(String searchText) {
        DefaultTableModel model = (DefaultTableModel) ServiceTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        ServiceTable.setRowSorter(sorter);
        
        if (searchText.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
        }
    }
    
    private void clear(){
        CboStatus.setSelectedIndex(0);
        cboProgress.setSelectedIndex(0);
      
    }
    
    private void setTableHeader(){
       TableColumn ColumnSet; 
        ServiceTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        JTableHeader THeader = ServiceTable.getTableHeader();
        THeader.setBackground(new Color(102, 102, 102));
        THeader.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        THeader.setForeground(Color.white);
        THeader.setFont(new Font("Seorge UI", Font.PLAIN, 18));
        
        for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
        try {
            // Set Nimbus look and feel
            UIManager.setLookAndFeel(info.getClassName());
            // Set the separator color in the table header
            UIManager.put("THeader.separatorColor", Color.BLACK);
        } catch (Exception e) {
            e.printStackTrace();
        }
        break;
    }
}
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        ServiceTable.getColumnModel().getColumn(0).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(1).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(2).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(3).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(4).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(5).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(6).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(7).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(8).setCellRenderer(renderer);
        
        
        
        ColumnSet = ServiceTable.getColumnModel().getColumn(0);//SID
        ColumnSet.setPreferredWidth(90);
        ColumnSet = ServiceTable.getColumnModel().getColumn(1);//SKU
        ColumnSet.setPreferredWidth(130);
        ColumnSet = ServiceTable.getColumnModel().getColumn(2);//BRAND
        ColumnSet.setPreferredWidth(130);
        ColumnSet = ServiceTable.getColumnModel().getColumn(3);//NAMA PELANGGAN
        ColumnSet.setPreferredWidth(330);
        ColumnSet = ServiceTable.getColumnModel().getColumn(4);//Tanggal Masuk
        ColumnSet.setPreferredWidth(228);
        ColumnSet = ServiceTable.getColumnModel().getColumn(5);//Status
        ColumnSet.setPreferredWidth(378);
        ColumnSet = ServiceTable.getColumnModel().getColumn(6);//Nama Petugas
        ColumnSet.setPreferredWidth(190);
        ColumnSet = ServiceTable.getColumnModel().getColumn(7);//Progress
        ColumnSet.setPreferredWidth(194);
        ColumnSet = ServiceTable.getColumnModel().getColumn(8);//Tanggal Selesai
        ColumnSet.setPreferredWidth(256);
       
        
        ServiceTable.setSelectionBackground(Color.GRAY);
    }
    
    private void isiCboStatus(){
        CboStatus.removeAllItems();
        CboStatus.addItem("Status");
        CboStatus.addItem("Produk akan segera diperiksa");
        CboStatus.addItem("Produk menunggu konfirmasi pelanggan");
        CboStatus.addItem("Produk sedang menunggu kedatangan sparepart");
        CboStatus.addItem("Produk sedang dalam proses perbaikan");
        CboStatus.addItem("Produk sudah selesai diperbaiki");
        CboStatus.addItem("Produk batal untuk dilakukan perbaikkan");
    }
    
    private void IsiCboProgress(){
        cboProgress.removeAllItems();
        cboProgress.addItem("Selesai/Proses/Batal");
        cboProgress.addItem("Proses");
        cboProgress.addItem("Batal");
        cboProgress.addItem("Selesai");
    }
    
    private void IsiTabel(){
        clsService tablefiller = new clsService();
        DefaultTableModel filler = new DefaultTableModel();
        filler.addColumn("SID");
        filler.addColumn("SKU");
        filler.addColumn("Brand");
        filler.addColumn("Nama Pelanggan");
        filler.addColumn("Tanggal Masuk");
        filler.addColumn("Status");
        filler.addColumn("Nama Petugas");
        filler.addColumn("Progress");
        filler.addColumn("Tanggal Selesai");
        try{
            tablefiller.show(ID);
            ResultSet rs = tablefiller.stat.executeQuery(tablefiller.sql);
            while(rs.next()){
                if(rs.getString(9) == null||rs.getString(9).equals("0000-00-00")||rs.getString(9).equals("")){
                    filler.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getDate(5), rs.getString(6), rs.getString(7), rs.getString(8), ""}); 
                }else{
                    filler.addRow(new Object[]{rs.getInt(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getDate(5), rs.getString(6), rs.getString(7), rs.getString(8), rs.getString(9)}); 
                }
                    
            }
            ServiceTable.setModel(filler);
            ServiceTable.getTableHeader().setResizingAllowed(false);
            ServiceTable.setDefaultEditor(Object.class, null);
            setTableHeader();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error Fetching");
            System.out.println(e.getMessage());
        }
    }
    
    
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        formMainMenu toMainMenu = new formMainMenu(Username, ID);
        this.dispose();
        toMainMenu.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void CboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboStatusActionPerformed

    private void ServiceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiceTableMouseClicked
        // TODO add your handling code here:
        int baris = ServiceTable.getSelectedRow();
        CboStatus.setSelectedItem(ServiceTable.getValueAt(baris, 5).toString());
        cboProgress.setSelectedItem(ServiceTable.getValueAt(baris, 7).toString());
    }//GEN-LAST:event_ServiceTableMouseClicked

    private void btnConfirmEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmEditActionPerformed
        // TODO add your handling code here:
        clsService Edit = new clsService();
       if(CboStatus.getSelectedItem().toString().equals("Produk sudah selesai diperbaiki") && cboProgress.getSelectedItem().toString().equals("Selesai")){
           try{
            Edit.Selesai(ServiceTable.getValueAt(ServiceTable.getSelectedRow(), 0).toString(), CboStatus.getSelectedItem().toString(), cboProgress.getSelectedItem().toString());
            Edit.stat.executeUpdate(Edit.sql);
            toogle = false;
            clear();
            btnCancel.setVisible(false);
            btnEdit.setVisible(true);
            btnConfirmEdit.setVisible(false);
            IsiTabel();
        }catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Gagal melakukan update terhadap database");
        }
       }else if(CboStatus.getSelectedItem().toString().equals("Produk batal untuk dilakukan perbaikkan") && cboProgress.getSelectedItem().toString().equals("Batal")){
            try{
            Edit.Selesai(ServiceTable.getValueAt(ServiceTable.getSelectedRow(), 0).toString(), CboStatus.getSelectedItem().toString(), cboProgress.getSelectedItem().toString());
            Edit.stat.executeUpdate(Edit.sql);
            toogle = false;
            
            clear();
            btnCancel.setVisible(false);
            btnEdit.setVisible(true);
            IsiTabel();
            }catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Gagal melakukan update terhadap database");
        }
       }else{
           try{
            Edit.edit(ServiceTable.getValueAt(ServiceTable.getSelectedRow(), 0).toString(), CboStatus.getSelectedItem().toString(), cboProgress.getSelectedItem().toString());
            Edit.stat.executeUpdate(Edit.sql);
            toogle = false;
            clear();
            btnCancel.setVisible(false);
            btnEdit.setVisible(true);
            IsiTabel();
            }catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Gagal melakukan update terhadap database");
        }
       }
    }//GEN-LAST:event_btnConfirmEditActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        clear();
        btnConfirmEdit.setVisible(true);
        toogle = true;
        btnCancel.setVisible(true);
        btnEdit.setVisible(false);
        
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        toogle = false;
        clear();
        btnConfirmEdit.setVisible(false);
        btnEdit.setVisible(true);
        btnCancel.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void CboStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CboStatusMouseClicked
        // TODO add your handling code here:
         if(toogle != true){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Aksi ini hanya dapat dilakukan jika tombol edit atau new bewarna hijau");
        }else{
            
        }
    }//GEN-LAST:event_CboStatusMouseClicked

    private void cboProgressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboProgressMouseClicked
        // TODO add your handling code here:
   
         if(toogle != true){
             evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Aksi ini hanya dapat dilakukan jika tombol edit atau new bewarna hijau");
        }else{
        
        }
         
    }//GEN-LAST:event_cboProgressMouseClicked

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        SwingUtilities.invokeLater(() -> {
        String searchText = txtSearch.getText().trim();
        searchTable(searchText);
    });
    }//GEN-LAST:event_txtSearchKeyTyped

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (posisi.width - this.getWidth())/2;
        int y = (posisi.height - this.getHeight())/2;
        this.setLocation(x, y);
    }//GEN-LAST:event_formWindowActivated

    /**
     * @param args the command line arguments
     */
    
    
    
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboStatus;
    private javax.swing.JLabel LabelProgress;
    private javax.swing.JLabel LabelSKU1;
    private javax.swing.JLabel LabelStatus;
    private javax.swing.JTable ServiceTable;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirmEdit;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cboProgress;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
