/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company.pbo.ServiceFunction;

import com.company.pbo.DBandConnect.clsDaftarList;
import ireport.CetakService;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;    
import java.sql.ResultSet;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.JTableHeader;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.table.TableRowSorter;



/**
 *
 * @author Mihaly
 */
public class formDaftarService extends javax.swing.JFrame {
    int ID;
    String Username;
    boolean toogle = false;

    /**
     * Creates new form formDaftarService
     */
    public formDaftarService(int ID, String Username) {
        this.ID = ID;
        this.Username = Username;
        initComponents();
        IsiTabel();
        isiCboStatus();
        IsiCboProgress();
        IsiCboPetugas();
        btnConfirmBaru.setVisible(false);
        btnConfirmEdit.setVisible(false);
        btnCancel.setVisible(false);
        btnHapus.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ServiceTable = new javax.swing.JTable();
        btnHapus = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnBaru = new javax.swing.JButton();
        LabelSKU = new javax.swing.JLabel();
        LabelBrand = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        LabelNoTelepon = new javax.swing.JLabel();
        LabelTglMasuk = new javax.swing.JLabel();
        LabelStatus = new javax.swing.JLabel();
        txtSKU = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtNamaPelanggan = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        CboStatus = new javax.swing.JComboBox<>();
        LabelPetugas = new javax.swing.JLabel();
        LabelProgress = new javax.swing.JLabel();
        cboPetugas = new javax.swing.JComboBox<>();
        cboProgress = new javax.swing.JComboBox<>();
        TanggalMasuk = new com.toedter.calendar.JDateChooser();
        btnConfirmBaru = new javax.swing.JButton();
        btnConfirmEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        LabelSKU1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuReport = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evoker Service");
        setBackground(new java.awt.Color(40, 43, 48));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(40, 43, 48));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setForeground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        ServiceTable.setBackground(new java.awt.Color(102, 102, 102));
        ServiceTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ServiceTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ServiceTable.setForeground(new java.awt.Color(255, 255, 255));
        ServiceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "X401D", "ASUS", "Kelvin", "081255519273", "11/12/22", "Sedang Diperiksa Oleh Petugas", "Dylan", "24", "Proses", null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SID", "SKU", "Brand", "Nama Pelanggan", "No. Telepon", "Tanggal Masuk", "Status", "Petugas", "ID Petugas", "Progress", "Tanggal Selesai"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ServiceTable.setToolTipText("");
        ServiceTable.setGridColor(new java.awt.Color(0, 0, 0));
        ServiceTable.setRowHeight(50);
        ServiceTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        ServiceTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ServiceTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        ServiceTable.setShowGrid(true);
        ServiceTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ServiceTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ServiceTable);
        if (ServiceTable.getColumnModel().getColumnCount() > 0) {
            ServiceTable.getColumnModel().getColumn(0).setResizable(false);
            ServiceTable.getColumnModel().getColumn(0).setPreferredWidth(50);
            ServiceTable.getColumnModel().getColumn(1).setResizable(false);
            ServiceTable.getColumnModel().getColumn(2).setResizable(false);
            ServiceTable.getColumnModel().getColumn(3).setResizable(false);
            ServiceTable.getColumnModel().getColumn(4).setResizable(false);
            ServiceTable.getColumnModel().getColumn(5).setResizable(false);
            ServiceTable.getColumnModel().getColumn(6).setResizable(false);
            ServiceTable.getColumnModel().getColumn(6).setPreferredWidth(258);
            ServiceTable.getColumnModel().getColumn(7).setResizable(false);
            ServiceTable.getColumnModel().getColumn(8).setResizable(false);
            ServiceTable.getColumnModel().getColumn(9).setResizable(false);
            ServiceTable.getColumnModel().getColumn(10).setResizable(false);
        }

        btnHapus.setBackground(new java.awt.Color(153, 0, 0));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(0, 0, 153));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnBaru.setBackground(new java.awt.Color(0, 0, 153));
        btnBaru.setForeground(new java.awt.Color(255, 255, 255));
        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        LabelSKU.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelSKU.setForeground(new java.awt.Color(255, 255, 255));
        LabelSKU.setText("SKU:");

        LabelBrand.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelBrand.setForeground(new java.awt.Color(255, 255, 255));
        LabelBrand.setText("Brand:");

        LabelNama.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelNama.setForeground(new java.awt.Color(255, 255, 255));
        LabelNama.setText("Nama Pemilik:");

        LabelNoTelepon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelNoTelepon.setForeground(new java.awt.Color(255, 255, 255));
        LabelNoTelepon.setText("No. Telepon:");

        LabelTglMasuk.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelTglMasuk.setForeground(new java.awt.Color(255, 255, 255));
        LabelTglMasuk.setText("Tanggal Masuk:");

        LabelStatus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelStatus.setForeground(new java.awt.Color(255, 255, 255));
        LabelStatus.setText("Status:");

        txtSKU.setBackground(new java.awt.Color(204, 204, 204));
        txtSKU.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSKU.setForeground(new java.awt.Color(0, 0, 0));
        txtSKU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSKUActionPerformed(evt);
            }
        });
        txtSKU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSKUKeyTyped(evt);
            }
        });

        txtBrand.setBackground(new java.awt.Color(204, 204, 204));
        txtBrand.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtBrand.setForeground(new java.awt.Color(0, 0, 0));
        txtBrand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBrandKeyTyped(evt);
            }
        });

        txtNamaPelanggan.setBackground(new java.awt.Color(204, 204, 204));
        txtNamaPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtNamaPelanggan.setForeground(new java.awt.Color(0, 0, 0));
        txtNamaPelanggan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNamaPelangganKeyTyped(evt);
            }
        });

        txtTelepon.setBackground(new java.awt.Color(204, 204, 204));
        txtTelepon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtTelepon.setForeground(new java.awt.Color(0, 0, 0));
        txtTelepon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTeleponKeyTyped(evt);
            }
        });

        CboStatus.setBackground(new java.awt.Color(153, 153, 153));
        CboStatus.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CboStatus.setForeground(new java.awt.Color(255, 255, 255));
        CboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CboStatus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CboStatusMouseClicked(evt);
            }
        });
        CboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CboStatusActionPerformed(evt);
            }
        });

        LabelPetugas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelPetugas.setForeground(new java.awt.Color(255, 255, 255));
        LabelPetugas.setText("Petugas:");

        LabelProgress.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelProgress.setForeground(new java.awt.Color(255, 255, 255));
        LabelProgress.setText("Progress:");

        cboPetugas.setBackground(new java.awt.Color(153, 153, 153));
        cboPetugas.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cboPetugas.setForeground(new java.awt.Color(255, 255, 255));
        cboPetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboPetugasMouseClicked(evt);
            }
        });

        cboProgress.setBackground(new java.awt.Color(153, 153, 153));
        cboProgress.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cboProgress.setForeground(new java.awt.Color(255, 255, 255));
        cboProgress.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboProgress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboProgressMouseClicked(evt);
            }
        });

        TanggalMasuk.setBackground(new java.awt.Color(204, 204, 204));
        TanggalMasuk.setForeground(new java.awt.Color(0, 0, 0));
        TanggalMasuk.setToolTipText("");
        TanggalMasuk.setDateFormatString("yyyy-MMM-d");
        TanggalMasuk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnConfirmBaru.setBackground(new java.awt.Color(0, 153, 0));
        btnConfirmBaru.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmBaru.setText("Confirm Baru");
        btnConfirmBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmBaruActionPerformed(evt);
            }
        });

        btnConfirmEdit.setBackground(new java.awt.Color(0, 153, 0));
        btnConfirmEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmEdit.setText("Confirm Edit");
        btnConfirmEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmEditActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(0, 0, 153));
        btnCancel.setForeground(new java.awt.Color(255, 255, 255));
        btnCancel.setText("Cancel Edit/New");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtSearch.setBackground(new java.awt.Color(204, 204, 204));
        txtSearch.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });

        LabelSKU1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LabelSKU1.setForeground(new java.awt.Color(255, 255, 255));
        LabelSKU1.setText("Cari:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(260, 260, 260)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(LabelPetugas)
                                    .addComponent(LabelStatus)
                                    .addComponent(LabelTglMasuk)
                                    .addComponent(LabelNoTelepon)
                                    .addComponent(LabelNama)
                                    .addComponent(LabelBrand)
                                    .addComponent(LabelSKU)
                                    .addComponent(LabelProgress)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(btnConfirmEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConfirmBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cboProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelSKU1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(13, 13, 13))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1907, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 6, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSKU, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSKU)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelSKU1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelBrand)
                    .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNama)
                    .addComponent(txtNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNoTelepon)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelTglMasuk)
                    .addComponent(TanggalMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelStatus))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPetugas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelProgress))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfirmEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE))
        );

        jMenuBar1.setForeground(new java.awt.Color(51, 51, 51));

        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("File");

        menuReport.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuReport.setText("Report");
        menuReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuReportActionPerformed(evt);
            }
        });
        jMenu1.add(menuReport);
        jMenu1.add(jSeparator1);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem3.setText("Back to Main Menu");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //user defined code
    
    private void searchTable(String searchText) {
        DefaultTableModel model = (DefaultTableModel) ServiceTable.getModel();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>(model);
        ServiceTable.setRowSorter(sorter);
        
        if (searchText.trim().length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + searchText));
        }
    }
    
    private void clear(){
        CboStatus.setSelectedIndex(0);
        cboPetugas.setSelectedIndex(0);
        cboProgress.setSelectedIndex(0);
        txtBrand.setText("");
        txtNamaPelanggan.setText("");
        txtSKU.setText("");
        txtTelepon.setText("");
        TanggalMasuk.setCalendar(null);
      
    }
    
    private void setTableHeader(){
        TableColumn ColumnSet; 
        ServiceTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        JTableHeader THeader = ServiceTable.getTableHeader();
        THeader.setBackground(Color.WHITE);
        THeader.setForeground(Color.black);
        THeader.setFont(new Font("Seorge UI", Font.PLAIN, 18));
        ((DefaultTableCellRenderer)THeader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        ServiceTable.getColumnModel().getColumn(0).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(1).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(2).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(3).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(4).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(5).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(6).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(7).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(8).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(9).setCellRenderer(renderer);
        ServiceTable.getColumnModel().getColumn(10).setCellRenderer(renderer);
        
        
        ColumnSet = ServiceTable.getColumnModel().getColumn(0);//SID
        ColumnSet.setPreferredWidth(70);
        ColumnSet = ServiceTable.getColumnModel().getColumn(1);//SKU
        ColumnSet.setPreferredWidth(130);
        ColumnSet = ServiceTable.getColumnModel().getColumn(2);//BRAND
        ColumnSet.setPreferredWidth(130);
        ColumnSet = ServiceTable.getColumnModel().getColumn(3);//NAMA PELANGGAN
        ColumnSet.setPreferredWidth(256);
        ColumnSet = ServiceTable.getColumnModel().getColumn(4);//NO TELEPON
        ColumnSet.setPreferredWidth(192);
        ColumnSet = ServiceTable.getColumnModel().getColumn(5);//TANGGAL MASUK
        ColumnSet.setPreferredWidth(156);
        ColumnSet = ServiceTable.getColumnModel().getColumn(6);//STATUS
        ColumnSet.setPreferredWidth(298);
        ColumnSet = ServiceTable.getColumnModel().getColumn(7);//ID PETUGAS
        ColumnSet.setPreferredWidth(120);
        ColumnSet = ServiceTable.getColumnModel().getColumn(8);//NAMA PETUGAS
        ColumnSet.setPreferredWidth(256);
        ColumnSet = ServiceTable.getColumnModel().getColumn(9);//PROGRESS
        ColumnSet.setPreferredWidth(130);
        ColumnSet = ServiceTable.getColumnModel().getColumn(10);//TANGGAL KELUAR
        ColumnSet.setPreferredWidth(163);
        
        ServiceTable.setSelectionBackground(Color.GRAY);
    }
    
    private void isiCboStatus(){
        CboStatus.removeAllItems();
        CboStatus.addItem("Status");
        CboStatus.addItem("Produk akan segera diperiksa");
        CboStatus.addItem("Produk menunggu konfirmasi pelanggan");
        CboStatus.addItem("Produk sedang menunggu kedatangan sparepart");
        CboStatus.addItem("Produk sedang dalam proses perbaikan");
        CboStatus.addItem("Produk sudah selesai diperbaiki");
        CboStatus.addItem("Produk batal untuk dilakukan perbaikkan");
    }
    
    private void IsiCboProgress(){
        cboProgress.removeAllItems();
        cboProgress.addItem("Selesai/Proses/Batal");
        cboProgress.addItem("Proses");
        cboProgress.addItem("Batal");
        cboProgress.addItem("Selesai");
    }
    
    private void IsiTabel(){
        clsDaftarList tablefiller = new clsDaftarList();
        DefaultTableModel filler = new DefaultTableModel();
        filler.addColumn("SID");
        filler.addColumn("SKU");
        filler.addColumn("Brand");
        filler.addColumn("Nama Pelanggan");
        filler.addColumn("No Telepon");
        filler.addColumn("Tanggal Masuk");
        filler.addColumn("Status");
        filler.addColumn("ID Petugas");
        filler.addColumn("Nama Petugas");
        filler.addColumn("Progress");
        filler.addColumn("Tanggal Selesai");
        try{
            tablefiller.Output();
            ResultSet rs = tablefiller.stat.executeQuery(tablefiller.sql);
           while (rs.next()){
                if(rs.getString(11) == null||rs.getString(11).equals("0000-00-00")||rs.getString(11).equals("")){
                    if(rs.getString(9) == null || rs.getString(9).equals("")){
                         filler.addRow(new Object[]{rs.getInt("SID"), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getDate(6), rs.getString(7), "", "", rs.getString(10), ""});
                    }else{
                        filler.addRow(new Object[]{rs.getInt("SID"), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getDate(6), rs.getString(7), rs.getInt(8), rs.getString(9), rs.getString(10), ""});
                    }
                }else{
                    if(rs.getString(9) == null || rs.getString(9).equals("")){
                        filler.addRow(new Object[]{rs.getInt("SID"), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getDate(6), rs.getString(7), "", "", rs.getString(10), rs.getString(11)}); 
                    }else{
                        filler.addRow(new Object[]{rs.getInt("SID"), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5), rs.getDate(6), rs.getString(7), rs.getInt(8), rs.getString(9), rs.getString(10), rs.getString(11)}); 
                    }
                    
                }    
            }
            ServiceTable.setModel(filler);
            setTableHeader();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Error Fetching");
            System.out.println(e.getMessage());
        }
    }
    
    private void IsiCboPetugas(){
        clsDaftarList cboFiller = new clsDaftarList();
        cboPetugas.removeAllItems();
        cboPetugas.addItem("Pilih Petugas");
        try{
        cboFiller.sql = "SELECT `Username`, `ID` FROM `akun` WHERE `ID` != '1001' ORDER BY `ID`;";
        ResultSet rs = cboFiller.stat.executeQuery(cboFiller.sql);
        while(rs.next()){
            cboPetugas.addItem( rs.getString("ID")+"-"+ rs.getString("Username"));
        }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Fetching Failed");
            System.out.println(e.getMessage());
        }
        
        
    }
    //user defined code
     
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        formMainMenu toMainMenu = new formMainMenu(Username, ID);
        this.dispose();
        toMainMenu.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void txtSKUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSKUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSKUActionPerformed

    private void CboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CboStatusActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Dimension Position = Toolkit.getDefaultToolkit().getScreenSize();
        int X = (Position.width - this.getWidth())/2;
        int Y = (Position.height - this.getHeight())/2;
        this.setLocation(X, Y);
    }//GEN-LAST:event_formWindowActivated

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        // TODO add your handling code here:
        clear();
        txtSKU.requestFocus();
       
        btnConfirmBaru.setVisible(true);
        cboProgress.removeItemAt(3);
        toogle = true;
        btnCancel.setVisible(true);
        btnEdit.setVisible(false);
        btnBaru.setVisible(false);
        btnHapus.setVisible(false);
        btnConfirmBaru.setVisible(true);
    }//GEN-LAST:event_btnBaruActionPerformed

    private void ServiceTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ServiceTableMouseClicked
        // TODO add your handling code here:
        int baris = ServiceTable.getSelectedRow();
        txtSKU.setText( ServiceTable.getValueAt(baris, 1).toString());
        txtBrand.setText(ServiceTable.getValueAt(baris, 2).toString());
        txtNamaPelanggan.setText( ServiceTable.getValueAt(baris, 3).toString());
        txtTelepon.setText(ServiceTable.getValueAt(baris, 4).toString());
        String dateStr = ServiceTable.getValueAt(baris, 5).toString();
        LocalDate localDate = LocalDate.parse(dateStr);
        Date date = Date.from(localDate.atStartOfDay(ZoneId.systemDefault()).toInstant());
        TanggalMasuk.setDate(date);
        CboStatus.setSelectedItem(ServiceTable.getValueAt(baris, 6).toString());
        cboPetugas.setSelectedItem(ServiceTable.getValueAt(baris, 7).toString() +"-"+ServiceTable.getValueAt(baris, 8).toString());
        cboProgress.setSelectedItem(ServiceTable.getValueAt(baris, 9).toString());
        if(toogle == true){
            btnHapus.setVisible(false);
        }else{
            btnHapus.setVisible(true);
        }
        
        
    }//GEN-LAST:event_ServiceTableMouseClicked

    private void btnConfirmBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmBaruActionPerformed
        // TODO add your handling code here:
        clsDaftarList Baru = new clsDaftarList();
        if(txtSKU.getText().isEmpty() || txtNamaPelanggan.getText().isEmpty() || txtNamaPelanggan.getText().isEmpty() || CboStatus.getSelectedIndex() == 0 || cboPetugas.getSelectedIndex() == 0 || cboProgress.getSelectedIndex() == 0 || TanggalMasuk.getDate() == null){
            JOptionPane.showMessageDialog(rootPane, "Seluruh form harus diisi", "WARNING", JOptionPane.WARNING_MESSAGE);
        }else{
             try{
                Baru.Save(txtSKU.getText(), txtBrand.getText(), txtNamaPelanggan.getText(), txtTelepon.getText(), TanggalMasuk.getDate(), CboStatus.getSelectedItem().toString(), cboPetugas.getSelectedItem().toString().substring(5), cboProgress.getSelectedItem().toString());
                Baru.stat.executeUpdate(Baru.sql);
                toogle = false;
               
                clear();
                btnCancel.setVisible(false);
                btnEdit.setVisible(true);
                IsiTabel();
            }catch(Exception e){
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(rootPane, "Gagal melakukan update terhadap database");
            }
        
        }   
    }//GEN-LAST:event_btnConfirmBaruActionPerformed

    private void btnConfirmEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmEditActionPerformed
        // TODO add your handling code here:
        clsDaftarList Edit = new clsDaftarList();
       if(txtSKU.getText().isEmpty() || txtNamaPelanggan.getText().isEmpty() || txtNamaPelanggan.getText().isEmpty() || CboStatus.getSelectedIndex() == 0 || cboPetugas.getSelectedIndex() == 0 || cboProgress.getSelectedIndex() == 0 || TanggalMasuk.getDate() == null){
            JOptionPane.showMessageDialog(rootPane, "Seluruh form harus diisi", "WARNING", JOptionPane.WARNING_MESSAGE);
        }else{
           if(CboStatus.getSelectedItem().toString().equals("Produk sudah selesai diperbaiki") && cboProgress.getSelectedItem().toString().equals("Selesai")){
           try{
            
            Edit.Selesai(ServiceTable.getValueAt(ServiceTable.getSelectedRow(), 0).toString(), CboStatus.getSelectedItem().toString(), cboProgress.getSelectedItem().toString());
            Edit.stat.executeUpdate(Edit.sql);
            toogle = false;
            clear();
            btnCancel.setVisible(false);
            btnBaru.setVisible(true);
            btnConfirmEdit.setVisible(false);
            btnEdit.setVisible(true);
            IsiTabel();
            JOptionPane.showMessageDialog(rootPane, "Update berhasil");
        }catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Gagal melakukan update terhadap database");
        }
       }else if(CboStatus.getSelectedItem().toString().equals("Produk batal untuk dilakukan perbaikkan") && cboProgress.getSelectedItem().toString().equals("Batal")){
            try{
            Edit.Selesai(ServiceTable.getValueAt(ServiceTable.getSelectedRow(), 0).toString(), CboStatus.getSelectedItem().toString(), cboProgress.getSelectedItem().toString());
            Edit.stat.executeUpdate(Edit.sql);
            toogle = false;
            clear();
            btnCancel.setVisible(false);
            btnBaru.setVisible(true);
            btnConfirmEdit.setVisible(false);
            btnEdit.setVisible(true);
            IsiTabel();
            JOptionPane.showMessageDialog(rootPane, "Update berhasil");
            }catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Gagal melakukan update terhadap database");
        }
       }else{
           try{
            Edit.Edit(ServiceTable.getValueAt(ServiceTable.getSelectedRow(), 0).toString(), txtSKU.getText(), txtBrand.getText(), txtNamaPelanggan.getText(), txtTelepon.getText(), TanggalMasuk.getDate(), CboStatus.getSelectedItem().toString(), cboPetugas.getSelectedItem().toString().substring(5), cboProgress.getSelectedItem().toString());
            Edit.stat.executeUpdate(Edit.sql);
            toogle = false;
            clear();
            btnCancel.setVisible(false);
            btnBaru.setVisible(true);
            btnConfirmEdit.setVisible(false);
            btnEdit.setVisible(true);
            IsiTabel();
            JOptionPane.showMessageDialog(rootPane, "Update berhasil");
            }catch(Exception e){
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(rootPane, "Gagal melakukan update terhadap database");
        }
       }
       }
       
       
       
    }//GEN-LAST:event_btnConfirmEditActionPerformed

    private void txtSKUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSKUKeyTyped
        // TODO add your handling code here:
        if(toogle != true){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Aksi ini hanya dapat dilakukan jika tombol edit atau new bewarna hijau");
        }else{
            if(txtSKU.getText().length() > 14){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Nama SKU dari produk tidak dapat melebihi dari 14 digit");
        }
        
        }
    }//GEN-LAST:event_txtSKUKeyTyped

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        clear();
        txtSKU.requestFocus();
        btnConfirmEdit.setVisible(true);
        toogle = true;
        btnCancel.setVisible(true);
        btnBaru.setVisible(false);
        btnEdit.setVisible(false);
        btnConfirmBaru.setVisible(false);
        btnHapus.setVisible(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        toogle = false;
        
       
        btnConfirmBaru.setVisible(false);
        btnConfirmEdit.setVisible(false);
        btnEdit.setVisible(true);
        btnBaru.setVisible(true);
        btnCancel.setVisible(false);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtBrandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBrandKeyTyped
        // TODO add your handling code here:
         if(toogle != true){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Aksi ini hanya dapat dilakukan jika tombol edit atau new bewarna hijau");
        }else{
            if(txtBrand.getText().length() > 30){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Nama Brand dari produk tidak dapat melebihi dari 30 digit");
        }
        }
    }//GEN-LAST:event_txtBrandKeyTyped

    private void txtNamaPelangganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNamaPelangganKeyTyped
        // TODO add your handling code here:
         if(toogle != true){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Aksi ini hanya dapat dilakukan jika tombol edit atau new bewarna hijau");
        }else{
             if(txtNamaPelanggan.getText().length() > 50){
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "Nama Pelanggan tidak dapat melebihi dari 50 digit");
            }
        }
    }//GEN-LAST:event_txtNamaPelangganKeyTyped

    private void txtTeleponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeleponKeyTyped
        // TODO add your handling code here:
         if(toogle != true){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Aksi ini hanya dapat dilakukan jika tombol edit atau new bewarna hijau");
        }else{
             if(txtTelepon.getText().length() > 15){
                evt.consume();
                JOptionPane.showMessageDialog(rootPane, "No telepon dari laptop tidak dapat melebihi dari 15 digit");
            }
        }
    }//GEN-LAST:event_txtTeleponKeyTyped

    private void CboStatusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CboStatusMouseClicked
        // TODO add your handling code here:
         if(toogle != true){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Aksi ini hanya dapat dilakukan jika tombol edit atau new bewarna hijau");
        }else{
            
        }
    }//GEN-LAST:event_CboStatusMouseClicked

    private void cboPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboPetugasMouseClicked
        // TODO add your handling code here:
   
         if(toogle != true){
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Aksi ini hanya dapat dilakukan jika tombol edit atau new bewarna hijau");
        }else{
        
        }
    }//GEN-LAST:event_cboPetugasMouseClicked

    private void cboProgressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboProgressMouseClicked
        // TODO add your handling code here:
   
         if(toogle != true){
             evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Aksi ini hanya dapat dilakukan jika tombol edit atau new bewarna hijau");
        }else{
        
        }
         
    }//GEN-LAST:event_cboProgressMouseClicked

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        clsDaftarList Hapus = new clsDaftarList();
        try{
            Hapus.Hapus(ServiceTable.getValueAt(ServiceTable.getSelectedRow(), 0).toString());
            Hapus.stat.executeUpdate(Hapus.sql);
            IsiTabel();
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Terjadi kesalahan dalam melakukan fungsi hapus");
            System.out.println(e.getMessage());
        }
       
    }//GEN-LAST:event_btnHapusActionPerformed

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        // TODO add your handling code here:
        btnHapus.setVisible(false);
    }//GEN-LAST:event_jPanel1MouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSearchActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        SwingUtilities.invokeLater(() -> {
        String searchText = txtSearch.getText().trim();
        searchTable(searchText);
    });
    }//GEN-LAST:event_txtSearchKeyTyped

    private void menuReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuReportActionPerformed
        // TODO add your handling code here:
        CetakService cetak = new CetakService();
        cetak.setVisible(true);
    }//GEN-LAST:event_menuReportActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    
    
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDaftarService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDaftarService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDaftarService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDaftarService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CboStatus;
    private javax.swing.JLabel LabelBrand;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelNoTelepon;
    private javax.swing.JLabel LabelPetugas;
    private javax.swing.JLabel LabelProgress;
    private javax.swing.JLabel LabelSKU;
    private javax.swing.JLabel LabelSKU1;
    private javax.swing.JLabel LabelStatus;
    private javax.swing.JLabel LabelTglMasuk;
    private javax.swing.JTable ServiceTable;
    private com.toedter.calendar.JDateChooser TanggalMasuk;
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnConfirmBaru;
    private javax.swing.JButton btnConfirmEdit;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JComboBox<String> cboPetugas;
    private javax.swing.JComboBox<String> cboProgress;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuReport;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtNamaPelanggan;
    private javax.swing.JTextField txtSKU;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
