/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.company.pbo;

import com.company.pbo.DBandConnect.clsAkun;
import java.awt.Dimension;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.Dimension;
import java.sql.ResultSet;
        

/**
 *
 * @author Mihaly
 */
public class forrmGantiUsername extends javax.swing.JFrame {
    int ID;
    String Username;
    /**
     * Creates new form GantiPassword
     */
    public forrmGantiUsername(int ID) {
        initComponents();
        this.ID = ID;
        MaxPassWarn.setVisible(false);
        SALAHPAS.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GantiPasswordlabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CurPass = new javax.swing.JPasswordField();
        btnKonfirmasi = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        MaxPassWarn = new javax.swing.JLabel();
        SALAHPAS = new javax.swing.JLabel();
        NewUsername = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Evoker Service");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        GantiPasswordlabel.setBackground(new java.awt.Color(255, 255, 255));
        GantiPasswordlabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        GantiPasswordlabel.setForeground(new java.awt.Color(255, 255, 255));
        GantiPasswordlabel.setText("GANTI USERNAME");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PASSWORD :");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERNAME:");

        CurPass.setBackground(new java.awt.Color(204, 204, 204));
        CurPass.setForeground(new java.awt.Color(0, 0, 0));
        CurPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                CurPassKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CurPassKeyTyped(evt);
            }
        });

        btnKonfirmasi.setBackground(new java.awt.Color(0, 153, 51));
        btnKonfirmasi.setText("Konfirmasi");
        btnKonfirmasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiActionPerformed(evt);
            }
        });

        btnBatal.setBackground(new java.awt.Color(204, 0, 0));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        MaxPassWarn.setForeground(new java.awt.Color(255, 0, 0));
        MaxPassWarn.setText("*Username harus 5-50 digit");

        SALAHPAS.setForeground(new java.awt.Color(255, 0, 0));
        SALAHPAS.setText("PASSWORD SALAH");

        NewUsername.setBackground(new java.awt.Color(204, 204, 204));
        NewUsername.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NewUsername.setForeground(new java.awt.Color(0, 0, 0));
        NewUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NewUsernameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NewUsernameKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnKonfirmasi)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(CurPass, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(NewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MaxPassWarn)
                    .addComponent(SALAHPAS))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(GantiPasswordlabel)
                .addGap(205, 205, 205))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(GantiPasswordlabel)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CurPass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SALAHPAS))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(MaxPassWarn)
                    .addComponent(NewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnKonfirmasi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKonfirmasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiActionPerformed
        // TODO add your handling code here:
        clsAkun newUsrnm = new clsAkun();
        if(CurPass.getPassword().length == 0 || NewUsername.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Kedua field harus diisi", "Warning", JOptionPane.WARNING_MESSAGE);
            CurPass.requestFocus();
        }else if(NewUsername.getText().length() < 5){
            JOptionPane.showMessageDialog(null, "Username baru tidak boleh kurang dari 5 digit", "Warning", JOptionPane.WARNING_MESSAGE);
            NewUsername.requestFocus();
        }else{
            try{
                ResultSet rs = newUsrnm.stat.executeQuery("SELECT `ID`, `Password` FROM `akun` WHERE `Password` = '"+String.valueOf(CurPass.getPassword())+"' AND ID = '"+ID+"'");
                if(rs.next()){
                    newUsrnm.gantiUsername(ID, NewUsername.getText());
                    try{
                        newUsrnm.stat.executeUpdate(newUsrnm.sql);
                        formAccountInfo toAKUN = new formAccountInfo(NewUsername.getText(), ID);
                        toAKUN.setVisible(true);
                        this.dispose();
                        JOptionPane.showMessageDialog(null, "Username telah terganti");
                    }catch(Exception e){
                        System.out.println(e.getMessage());
                    }
                    
                }else{
                    SALAHPAS.setVisible(true);
                }
                
            }catch(Exception e){
                System.out.println(e.getMessage());
            }
            
        }
    }//GEN-LAST:event_btnKonfirmasiActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        formAccountInfo akun = new formAccountInfo(Username, ID);
        akun.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        Dimension posisi = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (posisi.width - this.getWidth())/2;
        int y = (posisi.height - this.getWidth())/2;
        this.setLocation(x, y);
    }//GEN-LAST:event_formWindowActivated

    private void CurPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CurPassKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            evt.consume();
            NewUsername.requestFocus();
        }
    }//GEN-LAST:event_CurPassKeyPressed

    private void CurPassKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CurPassKeyTyped
        // TODO add your handling code here:
        if(CurPass.getPassword().length > 15){
             evt.consume();
         }
    }//GEN-LAST:event_CurPassKeyTyped

    private void NewUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NewUsernameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            evt.consume();
            btnKonfirmasi.requestFocus();
        }
    }//GEN-LAST:event_NewUsernameKeyPressed

    private void NewUsernameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NewUsernameKeyTyped
        // TODO add your handling code here:
        if(NewUsername.getText().length() > 49 || NewUsername.getText().length() < 5){
             MaxPassWarn.setVisible(true);
         }else{
            MaxPassWarn.setVisible(false);
        }
        if(NewUsername.getText().length() > 49){
             evt.consume();
         }
    }//GEN-LAST:event_NewUsernameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(forrmGantiUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(forrmGantiUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(forrmGantiUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(forrmGantiUsername.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField CurPass;
    private javax.swing.JLabel GantiPasswordlabel;
    private javax.swing.JLabel MaxPassWarn;
    private javax.swing.JTextField NewUsername;
    private javax.swing.JLabel SALAHPAS;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnKonfirmasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
